version: '3'
 
services:
 
  web:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
 
  db:
    image: postgres:11.2
    ports:
      - 5433:5432
    volumes:
      - .:/docker-entrypoint-initdb.d   <- (4)
