version: '3'
 
services:
 
  web:
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
 
  db:
    image: postgres:11.2
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - .:/docker-entrypoint-initdb.d
